#!/usr/bin/env bash
# Script that will display information about subdomains.

get_domain_info() {
	local domain="$1"
	local sub_domain="$2"
	
	subdomain=$(dig "$sub_domain.$domain" | grep -A1 'ANSWER SECTION:')
	record=$(echo "$subdomain" | awk 'NR>1 {print $4}')
	ip=$(echo "$subdomain" | awk 'NR>1 {print $5}')
	echo "The subdomain $sub_domain is a $record record and points to $ip"
}

if [ "$#" -eq 1 ]; then
	get_domain_info "$1" "www"
	get_domain_info "$1" "lb-01"
	get_domain_info "$1" "web-01"
	get_domain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	get_domain_info "$1" "$2"
fi
