#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirect = 'server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;'
sudo sed -i 's/server_name _;/$redirect/' /etc/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/server_name _/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
