#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server.
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install -y haproxy

server_config=\
"
frontend _frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend _backend
        balance roundrobin
		server 516579-web-01 54.236.30.138:80 check
		server 516579-web-02 100.25.188.43:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
