#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server.
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get update
sudo apt-get install -y haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 516579-web-01 3.236.147.89:80 check\n\tserver 516579-web-02 18.232.73.156:80 check\n' /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
