#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

echo "
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 516579-web-01:80 check
    server web-02 516579-web-02:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

sudo systemctl restart haproxy
