#!/usr/bin/env bash
# This is a Bash script that loops from 1 to 10.
# - It displays "Bad luck" for the 4th iteration.
# - It displays "Good luck" for the 8th iteration.
# - It displays "Best School" for other iterations.

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
		then
			echo "bad luck"
	elif [ $i -eq 7 ]
		then
			echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
